apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: flask-container
        image: an2071497/flaskimg:v1
        ports:
        - containerPort: 5000

# kubectl expose deployment <deployment-name> --type=NodePort --port=5000
# kubectl scale deployment <deployment-name> --replicas=5
# minikube service <service-name>