apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


# biruni@boma:~/Desktop/k8s-Flask$ kubectl create deployment backend --image=an2071497/flaskimg:v1
# biruni@boma:~/Desktop/k8s-Flask$ kubectl expose deployment backend --type=NodePort --port=5000
# biruni@boma:~/Desktop/k8s-Flask$ kubectl scale deployment backend --replicas=5
# biruni@boma:~/Desktop/k8s-Flask$ minikube service backend

